title: Beautiful Blog
author: GitHub User hwarn1
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Learn new things about me and cool facts about this amazing earth we live on!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  hwarn1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
